package com.cchong.logistics.entity;

public class CollectionFee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_fee.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_fee.c_date
     *
     * @mbg.generated
     */
    private String cDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_fee.mileage
     *
     * @mbg.generated
     */
    private String mileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_fee.c_starting
     *
     * @mbg.generated
     */
    private String cStarting;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_fee.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection_fee.c_type
     *
     * @mbg.generated
     */
    private String cType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_fee.c_id
     *
     * @return the value of collection_fee.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_fee.c_id
     *
     * @param cId the value for collection_fee.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_fee.c_date
     *
     * @return the value of collection_fee.c_date
     *
     * @mbg.generated
     */
    public String getcDate() {
        return cDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_fee.c_date
     *
     * @param cDate the value for collection_fee.c_date
     *
     * @mbg.generated
     */
    public void setcDate(String cDate) {
        this.cDate = cDate == null ? null : cDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_fee.mileage
     *
     * @return the value of collection_fee.mileage
     *
     * @mbg.generated
     */
    public String getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_fee.mileage
     *
     * @param mileage the value for collection_fee.mileage
     *
     * @mbg.generated
     */
    public void setMileage(String mileage) {
        this.mileage = mileage == null ? null : mileage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_fee.c_starting
     *
     * @return the value of collection_fee.c_starting
     *
     * @mbg.generated
     */
    public String getcStarting() {
        return cStarting;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_fee.c_starting
     *
     * @param cStarting the value for collection_fee.c_starting
     *
     * @mbg.generated
     */
    public void setcStarting(String cStarting) {
        this.cStarting = cStarting == null ? null : cStarting.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_fee.remarks
     *
     * @return the value of collection_fee.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_fee.remarks
     *
     * @param remarks the value for collection_fee.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection_fee.c_type
     *
     * @return the value of collection_fee.c_type
     *
     * @mbg.generated
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection_fee.c_type
     *
     * @param cType the value for collection_fee.c_type
     *
     * @mbg.generated
     */
    public void setcType(String cType) {
        this.cType = cType == null ? null : cType.trim();
    }
}