package com.cchong.logistics.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DriverInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.d_name
     *
     * @mbg.generated
     */
    private String dName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.d_sex
     *
     * @mbg.generated
     */
    private String dSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.d_uuid
     *
     * @mbg.generated
     */
    private String dUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.d_phone
     *
     * @mbg.generated
     */
    private String dPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.d_password
     *
     * @mbg.generated
     */
    private String dPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.card
     *
     * @mbg.generated
     */
    private String card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.d_balance
     *
     * @mbg.generated
     */
    private BigDecimal dBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_information.register_date
     *
     * @mbg.generated
     */
    private Date registerDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.d_id
     *
     * @return the value of driver_information.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.d_id
     *
     * @param dId the value for driver_information.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.d_name
     *
     * @return the value of driver_information.d_name
     *
     * @mbg.generated
     */
    public String getdName() {
        return dName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.d_name
     *
     * @param dName the value for driver_information.d_name
     *
     * @mbg.generated
     */
    public void setdName(String dName) {
        this.dName = dName == null ? null : dName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.d_sex
     *
     * @return the value of driver_information.d_sex
     *
     * @mbg.generated
     */
    public String getdSex() {
        return dSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.d_sex
     *
     * @param dSex the value for driver_information.d_sex
     *
     * @mbg.generated
     */
    public void setdSex(String dSex) {
        this.dSex = dSex == null ? null : dSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.d_uuid
     *
     * @return the value of driver_information.d_uuid
     *
     * @mbg.generated
     */
    public String getdUuid() {
        return dUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.d_uuid
     *
     * @param dUuid the value for driver_information.d_uuid
     *
     * @mbg.generated
     */
    public void setdUuid(String dUuid) {
        this.dUuid = dUuid == null ? null : dUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.d_phone
     *
     * @return the value of driver_information.d_phone
     *
     * @mbg.generated
     */
    public String getdPhone() {
        return dPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.d_phone
     *
     * @param dPhone the value for driver_information.d_phone
     *
     * @mbg.generated
     */
    public void setdPhone(String dPhone) {
        this.dPhone = dPhone == null ? null : dPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.d_password
     *
     * @return the value of driver_information.d_password
     *
     * @mbg.generated
     */
    public String getdPassword() {
        return dPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.d_password
     *
     * @param dPassword the value for driver_information.d_password
     *
     * @mbg.generated
     */
    public void setdPassword(String dPassword) {
        this.dPassword = dPassword == null ? null : dPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.card
     *
     * @return the value of driver_information.card
     *
     * @mbg.generated
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.card
     *
     * @param card the value for driver_information.card
     *
     * @mbg.generated
     */
    public void setCard(String card) {
        this.card = card == null ? null : card.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.d_balance
     *
     * @return the value of driver_information.d_balance
     *
     * @mbg.generated
     */
    public BigDecimal getdBalance() {
        return dBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.d_balance
     *
     * @param dBalance the value for driver_information.d_balance
     *
     * @mbg.generated
     */
    public void setdBalance(BigDecimal dBalance) {
        this.dBalance = dBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_information.register_date
     *
     * @return the value of driver_information.register_date
     *
     * @mbg.generated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_information.register_date
     *
     * @param registerDate the value for driver_information.register_date
     *
     * @mbg.generated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }
}