package com.cchong.logistics.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class FinanceInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.f_id
     *
     * @mbg.generated
     */
    private Integer fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.befor_money
     *
     * @mbg.generated
     */
    private BigDecimal beforMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.after_money
     *
     * @mbg.generated
     */
    private BigDecimal afterMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.f_money
     *
     * @mbg.generated
     */
    private BigDecimal fMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.f_type
     *
     * @mbg.generated
     */
    private String fType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.f_name_type
     *
     * @mbg.generated
     */
    private String fNameType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.f_ids
     *
     * @mbg.generated
     */
    private Integer fIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.f_name
     *
     * @mbg.generated
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finance_info.f_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date fDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.f_id
     *
     * @return the value of finance_info.f_id
     *
     * @mbg.generated
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.f_id
     *
     * @param fId the value for finance_info.f_id
     *
     * @mbg.generated
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.befor_money
     *
     * @return the value of finance_info.befor_money
     *
     * @mbg.generated
     */
    public BigDecimal getBeforMoney() {
        return beforMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.befor_money
     *
     * @param beforMoney the value for finance_info.befor_money
     *
     * @mbg.generated
     */
    public void setBeforMoney(BigDecimal beforMoney) {
        this.beforMoney = beforMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.after_money
     *
     * @return the value of finance_info.after_money
     *
     * @mbg.generated
     */
    public BigDecimal getAfterMoney() {
        return afterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.after_money
     *
     * @param afterMoney the value for finance_info.after_money
     *
     * @mbg.generated
     */
    public void setAfterMoney(BigDecimal afterMoney) {
        this.afterMoney = afterMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.f_money
     *
     * @return the value of finance_info.f_money
     *
     * @mbg.generated
     */
    public BigDecimal getfMoney() {
        return fMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.f_money
     *
     * @param fMoney the value for finance_info.f_money
     *
     * @mbg.generated
     */
    public void setfMoney(BigDecimal fMoney) {
        this.fMoney = fMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.f_type
     *
     * @return the value of finance_info.f_type
     *
     * @mbg.generated
     */
    public String getfType() {
        return fType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.f_type
     *
     * @param fType the value for finance_info.f_type
     *
     * @mbg.generated
     */
    public void setfType(String fType) {
        this.fType = fType == null ? null : fType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.f_name_type
     *
     * @return the value of finance_info.f_name_type
     *
     * @mbg.generated
     */
    public String getfNameType() {
        return fNameType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.f_name_type
     *
     * @param fNameType the value for finance_info.f_name_type
     *
     * @mbg.generated
     */
    public void setfNameType(String fNameType) {
        this.fNameType = fNameType == null ? null : fNameType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.f_ids
     *
     * @return the value of finance_info.f_ids
     *
     * @mbg.generated
     */
    public Integer getfIds() {
        return fIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.f_ids
     *
     * @param fIds the value for finance_info.f_ids
     *
     * @mbg.generated
     */
    public void setfIds(Integer fIds) {
        this.fIds = fIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.f_name
     *
     * @return the value of finance_info.f_name
     *
     * @mbg.generated
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.f_name
     *
     * @param fName the value for finance_info.f_name
     *
     * @mbg.generated
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finance_info.f_date
     *
     * @return the value of finance_info.f_date
     *
     * @mbg.generated
     */
    public Date getfDate() {
        return fDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finance_info.f_date
     *
     * @param fDate the value for finance_info.f_date
     *
     * @mbg.generated
     */
    public void setfDate(Date fDate) {
        this.fDate = fDate;
    }
}