package com.cchong.logistics.entity;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.infro_id
     *
     * @mbg.generated
     */
    private Integer infroId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.contents
     *
     * @mbg.generated
     */
    private String contents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.direction
     *
     * @mbg.generated
     */
    private String direction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.infro_id
     *
     * @return the value of notice.infro_id
     *
     * @mbg.generated
     */
    public Integer getInfroId() {
        return infroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.infro_id
     *
     * @param infroId the value for notice.infro_id
     *
     * @mbg.generated
     */
    public void setInfroId(Integer infroId) {
        this.infroId = infroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.contents
     *
     * @return the value of notice.contents
     *
     * @mbg.generated
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.contents
     *
     * @param contents the value for notice.contents
     *
     * @mbg.generated
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.direction
     *
     * @return the value of notice.direction
     *
     * @mbg.generated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.direction
     *
     * @param direction the value for notice.direction
     *
     * @mbg.generated
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }
}