package com.cchong.logistics.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.o_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.o_type
     *
     * @mbg.generated
     */
    private Integer oType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.contacts
     *
     * @mbg.generated
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.start_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.end_date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd",timezone = "GMT+8")
    //@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.shipping_address
     *
     * @mbg.generated
     */
    private String shippingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.receiving_address
     *
     * @mbg.generated
     */
    private String receivingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.s_id
     *
     * @mbg.generated
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.o_state
     *
     * @mbg.generated
     */
    private String oState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.e_id
     *
     * @mbg.generated
     */
    private Integer eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_information.o_remarks
     *
     * @mbg.generated
     */
    private String oRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.o_id
     *
     * @return the value of order_information.o_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.o_id
     *
     * @param oId the value for order_information.o_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.o_type
     *
     * @return the value of order_information.o_type
     *
     * @mbg.generated
     */
    public Integer getoType() {
        return oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.o_type
     *
     * @param oType the value for order_information.o_type
     *
     * @mbg.generated
     */
    public void setoType(Integer oType) {
        this.oType = oType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.contacts
     *
     * @return the value of order_information.contacts
     *
     * @mbg.generated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.contacts
     *
     * @param contacts the value for order_information.contacts
     *
     * @mbg.generated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.start_date
     *
     * @return the value of order_information.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.start_date
     *
     * @param startDate the value for order_information.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.end_date
     *
     * @return the value of order_information.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.end_date
     *
     * @param endDate the value for order_information.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.price
     *
     * @return the value of order_information.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.price
     *
     * @param price the value for order_information.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.shipping_address
     *
     * @return the value of order_information.shipping_address
     *
     * @mbg.generated
     */
    public String getShippingAddress() {
        return shippingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.shipping_address
     *
     * @param shippingAddress the value for order_information.shipping_address
     *
     * @mbg.generated
     */
    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress == null ? null : shippingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.receiving_address
     *
     * @return the value of order_information.receiving_address
     *
     * @mbg.generated
     */
    public String getReceivingAddress() {
        return receivingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.receiving_address
     *
     * @param receivingAddress the value for order_information.receiving_address
     *
     * @mbg.generated
     */
    public void setReceivingAddress(String receivingAddress) {
        this.receivingAddress = receivingAddress == null ? null : receivingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.s_id
     *
     * @return the value of order_information.s_id
     *
     * @mbg.generated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.s_id
     *
     * @param sId the value for order_information.s_id
     *
     * @mbg.generated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.d_id
     *
     * @return the value of order_information.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.d_id
     *
     * @param dId the value for order_information.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.o_state
     *
     * @return the value of order_information.o_state
     *
     * @mbg.generated
     */
    public String getoState() {
        return oState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.o_state
     *
     * @param oState the value for order_information.o_state
     *
     * @mbg.generated
     */
    public void setoState(String oState) {
        this.oState = oState == null ? null : oState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.e_id
     *
     * @return the value of order_information.e_id
     *
     * @mbg.generated
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.e_id
     *
     * @param eId the value for order_information.e_id
     *
     * @mbg.generated
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_information.o_remarks
     *
     * @return the value of order_information.o_remarks
     *
     * @mbg.generated
     */
    public String getoRemarks() {
        return oRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_information.o_remarks
     *
     * @param oRemarks the value for order_information.o_remarks
     *
     * @mbg.generated
     */
    public void setoRemarks(String oRemarks) {
        this.oRemarks = oRemarks == null ? null : oRemarks.trim();
    }
}