package com.cchong.logistics.entity;

public class VehicleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.i_id
     *
     * @mbg.generated
     */
    private Integer iId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.license
     *
     * @mbg.generated
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.v_type
     *
     * @mbg.generated
     */
    private String vType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.v_color
     *
     * @mbg.generated
     */
    private String vColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.t_type
     *
     * @mbg.generated
     */
    private Integer tType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.staff_no
     *
     * @mbg.generated
     */
    private Integer staffNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_info.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.i_id
     *
     * @return the value of vehicle_info.i_id
     *
     * @mbg.generated
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.i_id
     *
     * @param iId the value for vehicle_info.i_id
     *
     * @mbg.generated
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.license
     *
     * @return the value of vehicle_info.license
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.license
     *
     * @param license the value for vehicle_info.license
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.v_type
     *
     * @return the value of vehicle_info.v_type
     *
     * @mbg.generated
     */
    public String getvType() {
        return vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.v_type
     *
     * @param vType the value for vehicle_info.v_type
     *
     * @mbg.generated
     */
    public void setvType(String vType) {
        this.vType = vType == null ? null : vType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.v_color
     *
     * @return the value of vehicle_info.v_color
     *
     * @mbg.generated
     */
    public String getvColor() {
        return vColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.v_color
     *
     * @param vColor the value for vehicle_info.v_color
     *
     * @mbg.generated
     */
    public void setvColor(String vColor) {
        this.vColor = vColor == null ? null : vColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.t_type
     *
     * @return the value of vehicle_info.t_type
     *
     * @mbg.generated
     */
    public Integer gettType() {
        return tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.t_type
     *
     * @param tType the value for vehicle_info.t_type
     *
     * @mbg.generated
     */
    public void settType(Integer tType) {
        this.tType = tType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.staff_no
     *
     * @return the value of vehicle_info.staff_no
     *
     * @mbg.generated
     */
    public Integer getStaffNo() {
        return staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.staff_no
     *
     * @param staffNo the value for vehicle_info.staff_no
     *
     * @mbg.generated
     */
    public void setStaffNo(Integer staffNo) {
        this.staffNo = staffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_info.remarks
     *
     * @return the value of vehicle_info.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_info.remarks
     *
     * @param remarks the value for vehicle_info.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}