package com.cchong.logistics.entity;

import java.math.BigDecimal;

public class Vehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_id
     *
     * @mbg.generated
     */
    private Integer vId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.license
     *
     * @mbg.generated
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_type
     *
     * @mbg.generated
     */
    private String vType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.v_color
     *
     * @mbg.generated
     */
    private String vColor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.vload
     *
     * @mbg.generated
     */
    private BigDecimal vload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.d_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_id
     *
     * @return the value of vehicle.v_id
     *
     * @mbg.generated
     */
    public Integer getvId() {
        return vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_id
     *
     * @param vId the value for vehicle.v_id
     *
     * @mbg.generated
     */
    public void setvId(Integer vId) {
        this.vId = vId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.license
     *
     * @return the value of vehicle.license
     *
     * @mbg.generated
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.license
     *
     * @param license the value for vehicle.license
     *
     * @mbg.generated
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_type
     *
     * @return the value of vehicle.v_type
     *
     * @mbg.generated
     */
    public String getvType() {
        return vType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_type
     *
     * @param vType the value for vehicle.v_type
     *
     * @mbg.generated
     */
    public void setvType(String vType) {
        this.vType = vType == null ? null : vType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.v_color
     *
     * @return the value of vehicle.v_color
     *
     * @mbg.generated
     */
    public String getvColor() {
        return vColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.v_color
     *
     * @param vColor the value for vehicle.v_color
     *
     * @mbg.generated
     */
    public void setvColor(String vColor) {
        this.vColor = vColor == null ? null : vColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.vload
     *
     * @return the value of vehicle.vload
     *
     * @mbg.generated
     */
    public BigDecimal getVload() {
        return vload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.vload
     *
     * @param vload the value for vehicle.vload
     *
     * @mbg.generated
     */
    public void setVload(BigDecimal vload) {
        this.vload = vload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.d_id
     *
     * @return the value of vehicle.d_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.d_id
     *
     * @param dId the value for vehicle.d_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle.remarks
     *
     * @return the value of vehicle.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle.remarks
     *
     * @param remarks the value for vehicle.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}